title: Blog Posts
author: Ziraq Young
email: ziraqyoung@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A blog collection for Web Programming from JavaScript to Ruby.

# social links
twitter_username: youngziraq # DO NOT include the @ character, or else the build will fail!
github_username:  ziraqyoung # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
